# Generated by Django 3.0.5 on 2020-04-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=20000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('iphone', 'IPhone'), ('ipad', 'IPad'), ('mac', 'MacBook'), ('airpods', 'AirPods')], max_length=500)),
                ('users', models.ManyToManyField(related_name='trash', to='shop.UserModel')),
            ],
        ),
    ]
