# Generated by Django 3.0.5 on 2020-04-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='image',
            field=models.ImageField(blank=True, height_field=600, null=True, upload_to='images/', width_field=400),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='trash', to='shop.UserModel'),
        ),
    ]
